# artillery-config.yaml
config:
  target: "http://localhost:3000"
  phases:
    - duration: 600
      arrivalRate: 10
  defaults:
    headers:
      Content-Type: "application/json"

scenarios:
  - flow:
      - get:
          url: "/users"
      - get:
          url: "/products"
      - post:
          url: "/orders"
          json:
            userId: 1
            productId: 1
