version: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Configuration for Prometheus
    ports:
      - "9090:9090" # Prometheus web UI
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana # Persistent storage for Grafana
    ports:
      - "3000:3000" # Grafana web UI
  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100" # Node exporter
volumes:
  grafana_data:
