# prometheus.yml
global:
  scrape_interval: 15s # Scrape every 15 seconds

scrape_configs:
  - job_name: "node_exporter" # Scrape node exporter
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "docker" # Scrape Docker containers
    static_configs:
      - targets: ["host.docker.internal:9323"]
