global:
  scrape_interval: 2s # Scrape every 15 seconds

scrape_configs:
  - job_name: "node_exporter" # Scrape node exporter
    static_configs:
      - targets: ["host.docker.internal:9100"]

  - job_name: "docker" # Scrape Docker containers
    static_configs:
      - targets: ["host.docker.internal:9323"]

  - job_name: "cadvisor" # Scrape cAdvisor metrics
    static_configs:
      - targets: ["host.docker.internal:8080"]
